### ISSUE TITLE
Memory limit on transport page

### ISSUE THREAD

**Issue by golliholzland** [zenstruck/messenger-monitor-bundle#33]
it would be nice to add pagination on the transport queue  page **/admin/messenger/transport**. we handle large data, so the queues are long. and i get memory limit error when i try to check the status

**Comment by kbond** [comment]
I can add pagination but unfortunately it won't help. The entire list will still be loaded into memory because the Symfony contract doesn't support an offset - only a limit: https://github.com/symfony/symfony/blob/fafbbfac181fda0850548317f342da354cf9bbf2/src/Symfony/Component/Messenger/Transport/Receiver/ListableReceiverInterface.php#L32

**Comment by golliholzland** [comment]
maybe we set limit to 500 or something, at least we would be able to load the latest 500 message

**Comment by kbond** [comment]
> maybe we set limit to 500 or something, at least we would be able to load the latest 500 message

That seems reasonable.
